### PR TITLE
Prepare to migrate to the new versioning system

### PR DESCRIPTION
**Pull request by Digitalone1**
### Requirements 

* Filling out the template is required.
* All new code requires tests to ensure against regressions.
  - However, if your PR contains zero code changes, feel free to select the checkmark below to indicate so.

* [x] Have you ran tests against this code?

### Description of the Change

This is the first part of #64 and contains #62. I tried to introduce a view to help in sorting the versions but unfortunately it doesn't work because the order is lost while joining, so we are forced to write the ORDER BY clause every time we do a query.  

- Reverted part of the changes in #42
- Added created/updated timestamps to versions table, plus the update trigger
- New code refactoring using the new ORDER BY clause
- Started to ignore the latest status (which will be dropped in the future) and selecting the latest version relying on the sorting method
- Introduce the DISTINCT ON PostgreSQL extension to select the latest versions and make use of Common Table Expressions
- Fixed the existing sorting method introducing a new `getOrderField` internal function to retrieve the proper column
- Added new tests for the sorting system (moved the deletion tests at the end)

### CODE REVIEW

**Comment by confused-Techie** [comment]
Thanks a ton for this! I'm reviewing the code now and just to confirm, that if this is merged we are good to push our backlog of changes to prod (With of course the needed db changes) correct?

But again thanks for the contribution!

**Comment by Digitalone1** [comment]
Yes, but maybe it's better to wait for the other changes in #64

**Comment by confused-Techie** [comment]
> Yes, but maybe it's better to wait for the other changes in #64

Copy that! Sounds like a plan

**Review by confused-Techie — APPROVED** [review]
Overall these changes look good. I'll want to dig a little deeper during testing. but at a readonly review this is looking great so far, and looks like it's changing exactly what has been discussed previously.

Like the cleaning up of our tests, and bundling the Names Supply Chain Attack fixes in here.
Thanks for all the effort!

**Pull request merged**
