### PR TITLE
Fix requesting `package.json` when posting a new package version

### PR DESCRIPTION
**Pull request by PolariTOON**
### Requirements 

* Filling out the template is required.
* All new code requires tests to ensure against regressions.
  - However, if your PR contains zero code changes, feel free to select the checkmark below to indicate so.

* [ ] Have you ran tests against this code?
* [ ] This PR contains zero code changes.

### Description of the Change

`packExists.name` does not exist, this should be `packExists.content.name` or `params.packageName`.
Hopefully this should fix the "The package.json at owner/repo isn't valid." error when attempting to publish a package.

### CODE REVIEW

**Comment by Digitalone1** [comment]
It's better if we use `packExists.content.name` because we use the one directly from the packages table. The one provided on the request may be a previous name used before a rename.

**Review by confused-Techie — CHANGES_REQUESTED** [review]
So first off, thanks a ton for the contribution!

But there are a few notes I'd like to add here.

* You are correct that `packExists.name` doesn't exist, and is likely causing this error.
* @Digitalone1 is also correct, that following our convention (of trusting Query Parameters as little as possible) we would likely want to address this object via `packExists.content.name` since that's what the DB should be returning, and is a reason we are calling it here to get it's safe normalized data. In tasks like this you want to trust user input as little as possible, since it's possible there could be unknown or unsafe data hidden within the parameters like this, as you should always assume when working with user data. So that's really the change I'm requesting on this review.
* Otherwise I wanted to add I'm not confident this will fully solve the issue. The second part to this problem is one I've been thinking on how best to solve. Which I'll detail more below:

This endpoint has to support renaming a package, which is mostly where the complexity comes in. 

As you can see later here we then attempt to lookup the GitHub Repo `package.json` by looking for the repo `https://github.com/${user.content.username}/${packExists.name}` The biggest issues here, is obviously the name that we have already pointed out, the other is two fold.

When a user renames their package with us, how do we know they haven't already renamed the repo where it lives? The name we use here is what we know it previously was, but it might not still be that. Additionally, the name we have saved for a user is their `login` name, not necessarily their display name, or the name that would be used on the package say if they published a package for an org they have write access to. In those cases this will still fail 100% of the time.

Likely what we want to do here, is not use the name at all, since even with everything I've said the name of your package can be anything, it doesn't have to match the actual repo name at all.

What we should do is extract the `owner/repo` combo from the repository field of our known good data, and from there check if we can get the `package.json` in that repo.

I realize what I've said here is outside the scope of your PR, but writing long form answers like this helps me to think out the issue, and while I'd recommend making the changes to use the DB return, eventually we will need to change this to rely on the repo info of the DB return, and scrape anything to do with the username and package name, as they are not reliable in determining a URL to access the repos data at all.

@Digitalone1 thought I should loop you in on this if you wanted to add your two cents on the possible solution, since you're fantastic of thinking of edge cases

**Comment by Digitalone1** [comment]
@confused-Techie Your argument is good. I'm not an expert on Github API, but if using the login name along with the package name is a robust way for getting the package data, that's ok.

So, for getting the repo info you're saying we have to extract username and package name from the `data` json field?

**Comment by Digitalone1** [comment]
Taking this anche extract `repo/name`?

https://github.com/pulsar-edit/package-backend/blob/main/docs/resources/package_object_full.json#L5

**Comment by Digitalone1** [comment]
Here is a regex that can be used to extract the needed string based on various formats:

https://regex101.com/r/3OMBy2/1

**Comment by confused-Techie** [comment]
> Here is a regex that can be used to extract the needed string based on various formats:
> 
> https://regex101.com/r/3OMBy2/2
> 
> Update: A version without backtracking using the positive lookahead, but for this we first have to remove the eventual final `.git`:
> 
> https://regex101.com/r/I5p3OT/1

This is beautiful, and you are exactly right we need to use this to work with the package data on GitHub, to support someone publishing on the behalf of an org, or if their login name is different than their display name and so on.

So this looks like it could be perfect, but yeah we could check for removing an ending `.git` or other misc data, but using this could be a huge step up.

Since we aren't seeing much from the original author, I may try to get to this soon.

Thanks for writing that up!

**Comment by Digitalone1** [comment]
@PolariTOON your change have been included in #23 

@confused-Techie if it's okay to you, this one can be closed.

**Pull request merged**
