### PR TITLE
[FEAT] Serve Swagger from /swagger-ui

### PR DESCRIPTION
**Pull request by kyjus25**
### Requirements 

* Filling out the template is required.
* All new code requires tests to ensure against regressions.
  - However, if your PR contains zero code changes, feel free to select the checkmark below to indicate so.

* [x] Have you ran tests against this code?
* [ ] This PR contains zero code changes.

### Description of the Change

Exposes a Swagger from `/swagger-ui` using the spec that @Spiker985 created

### CODE REVIEW

**Comment by Spiker985** [comment]
Super excited for this, though I know that I need to update that definition a bit more. The eventual hope is to have the definition be generated via the existing JSDocs used to make api.md

**Comment by kyjus25** [comment]
@Spiker985 I was going to implement that, but felt bad generating everything you just hand did 😅

Also, for anyone testing this, the prod server will block the requests since it's coming from localhost. Hence why I added localhost as an option in the servers. If/When this is a generated spec we'll be able to programmatically call in the version and server info and stuff.

**Comment by Spiker985** [comment]
Oh no, by all means automate it's generation

I only manually made one since I didn't know offhand how to go about performing the generation in a consistent and concise manner

It also made sense to me to have a handwritten one as a basis for making sure the automation was working properly

**Review by confused-Techie — APPROVED** [review]
This looks good to me. Won't lie a part of me doesn't like seeing the HTML return on the backend, but otherwise this looks good to me.

Now I would love to see OPTIONS support added also to this new endpoint, but not a blocker for this PR. Otherwise looks great!

**Review by confused-Techie — CHANGES_REQUESTED** [review]
Sorry, I approved before reviewing the tests.

We have a test that checks the return of `/` in `integration_tests` and it's failing now that this returns an HTML response rather than the JSON.

So that test will need to be fixed

**Comment by kyjus25** [comment]
@confused-Techie I thought it be helpful for new recruits to have some immediate help when they go to the port for the first time. However, I could just as easily note it in the readme. I can move it 🤷🏼‍♂️

**Comment by confused-Techie** [comment]
@kyjus25 No no, it's a good change. I was mostly joking about that, but this landing page makes way more sense than just JSON returning the version

**Comment by kyjus25** [comment]
@confused-Techie test is updated

**Comment by confused-Techie** [comment]
Thanks for addressing the tests, this looks awesome, love it!

**Comment by Spiker985** [comment]
Ironically enough, we will need to update the definition to change what the `/` endpoint returns now :rofl:

**Pull request merged**
