### PR TITLE
More robust owner/repo retrieving + SQL query optimization

### PR DESCRIPTION
**Pull request by Digitalone1**
### Requirements 

* [x] Have you ran tests against this code?

### Description of the Change

As the title says, a more robust version for getting the `owner/repo` string. We pass the package and extract the string making an attempt on multiple properties (more can be added in the future in case GitHub changes the package format).

The regex has been slightly fixed to allow the same characters on both owner and repo. More tests have been added.

For an easier reviewing, it's recommended to push #19 before.

### CODE REVIEW

**Comment by confused-Techie** [comment]
I've gone ahead and merged #19 but looks like you may need to rebase to get a simpler review. Otherwise I'll still try and take a look

**Comment by Digitalone1** [comment]
> I've gone ahead and merged #19 but looks like you may need to rebase to get a simpler review. Otherwise I'll still try and take a look

I will try to merge the main branch.

**Comment by Digitalone1** [comment]
No luck in merging the main branch. I will try to make another PR close this one.

**Comment by Digitalone1** [comment]
My bad, I merged the origin one. Now I merged the upstream/main and the conflicts are gone.

@confused-Techie you can review when have time.

**Comment by Digitalone1** [comment]
I'm doing other things on this so for the moment I make it as a draft.

**Comment by Digitalone1** [comment]
I know it would have been better to make another branch, but with all the recent issues with conflicts it's better If I make a single one.

The latest changes are about
-  using `utils.getOwnerRepoFromPackage()` also for other `git.ownership()` calls where the repo has to be extracted by the package
- using @PolariTOON changes
- using the `owner/repo` string in other parts of package_handler code where it's needed
- optimize queries prefering INNER JOIN over IN as suggested by @mauricioszabo
- add tests for `database.getPackageCollectionByName`

**Review by confused-Techie — APPROVED** [review]
This looks good to me!
There's a lot of changes here, but tests are passing and they all look super valid. While I can't speak to the exact execution of the SQL statements I read through these being developed on Discord.

So I'll go ahead and merge this one quickly in the high hopes that it does in fact resolve our package maintainer issues.

Otherwise really like the way you redeclared variables during tests against our new utility function, makes things way easier to confirm them working without having to retype anything.

Plus while the `data.repository` field should always be available since it's creating when a package is published, good idea on being as careful as possible here.

Maybe once we confirm this methodology works we could even add a warning when it has to do this as it shows the package data itself is malformed on the backend.

But this is an issue for another day, appreciate the contribution as always!

**Pull request merged**
