### PR TITLE
Add `owner` field to `packages` table…

### PR DESCRIPTION
**Pull request by savetheclocktower**
…along with a script for extracting the owner from the repo URL.

### Description of the Change

Add an `owner` field to the packages table. The goal here is eventually to allow the frontend to query all packages that are owned by a specific GitHub organization.

This is a distinct concept from the backend's (or frontend's) idea of a “user,” since a user can publish a package to an organization they don't own. For example, the `linter-eslint-node` package was owned by the `AtomLinter` organization, and a user would expect to see as much when looking at the package card on the frontend. If they clicked on `AtomLinter`, they'd want to see other packages owned by `AtomLinter`. The fact that _I_, user `savetheclocktower`, was usually the one publishing those packages is irrelevant.

### CODE REVIEW

**Comment by confused-Techie** [comment]
Taking a quick look here, overall these changes look fantastic!

Love especially that you took the chance to fix some minor errors in docs, as well as renaming the variables for pagination like you mentioned in #213.

The only thing I'd be super concerned about besides testing which we are discussing on Discord, is to ensure that all other pagination returns match the new names used here. Since if memory serves theres a couple more endpoints that utilize this.

**Comment by savetheclocktower** [comment]
OK, the tests are passing, so I'm going to take this out of draft.

@confused-Techie, let me know what you think of the `add-owner-field.js` script and whether it should behave any differently. I don't have a great way of testing it, but it was working in the contrived scenario I set up.

**Review by confused-Techie — APPROVED** [review]
After fully reviewing the code this looks great!
I may slightly change the script to ensure it's easily runnable from the CLI the same way others are, but otherwise this is fantastic!

I appreciate the time you took to ensure things are as well tested as allowed to be currently, additionally taking the time to fix any linter warnings, and ensuring ESLint was as happy as can be.

This PR is remarkably complete, handling edge cases, handling initial migration, and even ensuring things are displayed later on. Especially love the time you took to ensure the data is easily available on every single different query to the DB that returns package data.

Seriously impressed, and with the tests being happy, it seems to me we are good to merge.

---

An aside for expectations, after merging, I'll need to run the migrations for the DB to include these changes. And hoping there are no errors, afterwards I can go ahead and push these changes to production for everyone to take advantage of, and especially then get an `owner` endpoint functional on the backend.

Thanks again for all your work here!

**Comment by savetheclocktower** [comment]
No problem! Don't have write access to this repo, so this one is on you to merge.

**Pull request merged**
