### PR TITLE
New pagination system

### PR DESCRIPTION
**Pull request by Digitalone1**
### Requirements 

* [x] Have you ran tests against this code?

### Description of the Change

This takes commits from #6 and introduces a more efficient pagination system using the postgreSQL window function `OVER()`.

### CODE REVIEW

**Comment by Digitalone1** [comment]
@confused-Techie I don't understand what CodeQL is complaining about.

**Comment by confused-Techie** [comment]
> @confused-Techie I don't understand what CodeQL is complaining about.

Don't worry about this one, it's complaining about possible log injection from the temp logs I've got set up, so nothing on your PR

**Comment by kyjus25** [comment]
Just gave it a test and it works beautifully! Excellent work, @Digitalone1, thanks for tag-teaming this with me

**Review by confused-Techie — APPROVED** [review]
Finally got to testing this one.

Looks great, and seems like it should work without issue.

Thanks a ton for the contribution!

**Pull request merged**
